name: 'Feishu Robot'
description: 'A simple feishu robot by github action'
author: 'Zero <GitHub: whatwewant>'
branding:
  icon: 'message-square'
  color: 'green'
color:
inputs:
  url:
    required: true
    description: web hook url
  title:
    required: true
    description: the msg title
  text:
    required: true
    description: the msg body
  at:
    required: false
    description: the msg metion to
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: docker
  image: Dockerfile
  # entrypoint: 'sh -c'
  # args:
  #   - node /app/lib/action.js
  env:
    ACTION_URL: ${{ inputs.url }}
    ACTION_TITLE: ${{ inputs.title }}
    ACTION_TEXT: ${{ inputs.text }}
    ACTION_AT: ${{ inputs.at }}
